version: '3'
services:
  db:
    image: postgres:10.1-alpine
    restart: always
    container_name: db-service
    ports:
      - 5444:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
