version: '3'
services:
  db:
    image: postgres:10.1-alpine
    restart: always
    container_name: db-service
    ports:
      - 5444:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
  app:
    build: ./
    restart: always
    container_name: app-service
    command: python -u main.py
#    volumes:
#      - :/data

    environment:
      - CRON=* * * * *
      - DB_PORT=5432
      - DB_HOST=db-service
#      - FILE_PATH=../data/1.json
    depends_on:
      - db
